# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "CI"

on:
  pull_request:
    branches:
      - "master"
      - "*.x"
  push:
    branches:
      - "master"
      - "*.x"
    tags:
      - "*"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "1.99.99"

jobs:

  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          coverage: "none"
          tools: "composer"
      - uses: "ramsey/composer-install@v3"
      - name: "Lint the PHP source code"
        run: "./vendor/bin/parallel-lint src test"

  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          coverage: "none"
          ini-values: "memory_limit=-1"
          tools: "composer"
      - uses: "ramsey/composer-install@v3"
      - name: "Check coding standards"
        run: "./vendor/bin/phpcs"

  static-analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          coverage: "none"
          ini-values: "memory_limit=-1"
          tools: "composer"
      - uses: "ramsey/composer-install@v3"
      - name: "Analyze code for errors"
        run: "./vendor/bin/phpstan"

  coverage:
    name: "Coverage"
    needs: ["coding-standards", "lint", "static-analysis"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          coverage: "xdebug"
          ini-values: "memory_limit=-1, zend.assertions=1, error_reporting=-1, display_errors=On"
          tools: "composer"
      - uses: "ramsey/composer-install@v3"
      - name: "Run unit tests"
        run: "./vendor/bin/phpunit --colors=always --coverage-clover build/logs/clover.xml --coverage-text"
      - name: "Publish coverage report to Codecov"
        uses: "codecov/codecov-action@v5"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  unit-tests:
    name: "Unit Tests"
    needs: ["coverage"]
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "memory_limit=-1, zend.assertions=1, error_reporting=-1, display_errors=On"
          tools: "composer"
      - uses: "ramsey/composer-install@v3"
      - name: "Run unit tests"
        run: "./vendor/bin/phpunit --colors=always --no-coverage"
